### ISSUE TITLE
divide by 0

### ISSUE THREAD

**Issue by jack-nie** [liberize/liberize.github.com#1]
当tag数目不足时，例如只发了一篇博客，会出现这个错误，导致无法启动。我看了一下，在tagcloud这个文件下，对于diff的处理有点问题，如果diff为0是不能作为除数的，这里需要判断一下。

**Comment by liberize** [comment]
这个博客好久没维护了，顺手 fix 了，连同另一个搜索的 bug，我本地没有环境，请帮忙测一下，谢谢。

**Comment by jack-nie** [comment]
恩，之前没用过搜索功能。。现在拉下来试了下，没问题。。。
PS博客风格是我喜欢的类型，所以就借用了。。希望不要介意_^_
再PS用手机端访问就有点不那么完美了。

**Comment by liberize** [comment]
欢迎 fork，移动端没有做适配。
