### ISSUE TITLE
非常好看的模板

### ISSUE THREAD

**Issue by heartnn** [liberize/liberize.github.com#2]
这是我见过的最符合国人的博客风格模板，请问是否能以此修改自用？绝不会用于商业用途，并会保留based on 您的博客链接。

**Comment by liberize** [comment]
用吧，不要客气 ^_^，不过要记得把 config.yml 里面我的信息改成你自己的
2015年7月17日 19:40于 "heartnn" notifications@github.com写道：

**Comment by heartnn** [comment]
非常感谢。
